/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import TravelAgency.AirPlane;
import TravelAgency.AirPlaneDirectory;
import TravelAgency.Airliner;
import TravelAgency.Flight;
import TravelAgency.FlightDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class ManageFlightJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageFlightJpanel
     */
    private JPanel rightpanel;
    private Airliner airliner;
    private AirPlane airplane;
    private AirPlaneDirectory apdir;
    private FlightDirectory fdir;
    //private Flight flight;
    SimpleDateFormat ymd =   new SimpleDateFormat( "yyyy-MM-dd" );
    SimpleDateFormat hm =   new SimpleDateFormat( "HH:mm" );
    public ManageFlightJpanel(JPanel rightpanel,Airliner airliner,AirPlane airplane) {
        initComponents();
       
        this.rightpanel = rightpanel;
        this.airliner = airliner;
        this.airplane = airplane;
        AirlinerNameTxt.setText(airliner.getName());
        AirPlaneNameTxt1.setText(airplane.getName());
        //fdir = new FlightDirectory();
        //airplane.setFlightDirectory(fdir);
        populate();
    }
    
    public void populate(){
        int rowCount = FlightTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)FlightTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        
        for(Flight f  : airplane.getFlightDirectory().getFlightdirectory()){
            Object row[] = new Object[dtm.getColumnCount()];
            row[0] = f;
            row[1] = ymd.format(f.getDate());
            row[2] = hm.format(f.getDepaturetime());
            row[3] = f.getFrom();
            row[4] = f.getTo();
            row[5] = f.getPrice();
            
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        AirlinerNameTxt = new javax.swing.JTextField();
        AirPlaneNameTxt1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();
        createBtn = new javax.swing.JButton();
        ViewBtn = new javax.swing.JButton();
        BackBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("Manage Flight");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 0, 206, 43));

        jLabel2.setFont(new java.awt.Font("Myanmar MN", 1, 16)); // NOI18N
        jLabel2.setText("Airliner Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 51, 129, 26));
        add(AirlinerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(157, 49, 123, 32));
        add(AirPlaneNameTxt1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 49, 123, 32));

        jLabel3.setFont(new java.awt.Font("Myanmar MN", 1, 16)); // NOI18N
        jLabel3.setText("AirPlane Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 51, 129, 26));

        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Date", "Time", "From", "To", "Price"
            }
        ));
        jScrollPane1.setViewportView(FlightTable);
        if (FlightTable.getColumnModel().getColumnCount() > 0) {
            FlightTable.getColumnModel().getColumn(0).setResizable(false);
            FlightTable.getColumnModel().getColumn(5).setResizable(false);
        }

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 99, 691, 216));

        createBtn.setBackground(new java.awt.Color(255, 255, 255));
        createBtn.setText("New Flight");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBtnActionPerformed(evt);
            }
        });
        add(createBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 333, 129, -1));

        ViewBtn.setBackground(new java.awt.Color(255, 255, 255));
        ViewBtn.setText("View Flight");
        ViewBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBtnActionPerformed(evt);
            }
        });
        add(ViewBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(312, 333, 132, -1));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back<<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 450, 127, -1));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Delete Flight");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(581, 333, 132, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBtnActionPerformed
        // TODO add your handling code here:
        CreateFlightJpanel cfpanel = new CreateFlightJpanel (rightpanel,airliner,airplane);
        this.rightpanel.add(cfpanel);
        CardLayout layout = (CardLayout)this.rightpanel.getLayout();
        layout.next(rightpanel);
    }//GEN-LAST:event_createBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int selectedRow = FlightTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Flight flight = (Flight)FlightTable.getValueAt(selectedRow, 0);
                airplane.getFlightDirectory().deleteFlight(flight);
                populate();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void ViewBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBtnActionPerformed
        // TODO add your handling code here:
        
        int selectedRow = FlightTable.getSelectedRow();
        if(selectedRow >= 0){
            Flight flight= (Flight)FlightTable.getValueAt(selectedRow, 0);
            ViewFlightJpanel vfpanel =  new ViewFlightJpanel(rightpanel,airliner,airplane,flight);
            this.rightpanel.add(vfpanel);
            CardLayout layout = (CardLayout)this.rightpanel.getLayout();
            layout.next(rightpanel);
        }
        else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_ViewBtnActionPerformed

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        Component[] componentArray = rightpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirplaneJpanel appanel = (AirplaneJpanel) component;
        appanel.populate();
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AirPlaneNameTxt1;
    private javax.swing.JTextField AirlinerNameTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTable FlightTable;
    private javax.swing.JButton ViewBtn;
    private javax.swing.JButton createBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
