/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import TravelAgency.AirPlaneDirectory;
import TravelAgency.Airliner;
import TravelAgency.AirlinerDirectory;
import UserInterface.TravelAgency.ManageAirliner;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JPanel;
import UserInterface.Airliner.AirlinerLoginJpanel;

/**
 *
 * @author liumingyu
 */
public class ManageAirplaneJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageAirplane
     */
    private JPanel airlinerpanel;
    private Airliner airliner;
    public ManageAirplaneJpanel(JPanel airlinerpanel,Airliner airliner) {
        initComponents();
        this.airlinerpanel = airlinerpanel;
        this.airliner = airliner;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ManageAirplaneBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageAirplaneBtn.setBackground(new java.awt.Color(255, 255, 255));
        ManageAirplaneBtn.setText("Manage Airplane");
        ManageAirplaneBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ManageAirplaneBtnActionPerformed(evt);
            }
        });
        add(ManageAirplaneBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 202, 37));

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("Manage Airplane");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 20, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void ManageAirplaneBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ManageAirplaneBtnActionPerformed
        // TODO add your handling code here:
        AirplaneJpanel apanel = new AirplaneJpanel(airlinerpanel,airliner);
        this.airlinerpanel.add(apanel);
        CardLayout layout = (CardLayout)this.airlinerpanel.getLayout();
        layout.next(airlinerpanel);
    }//GEN-LAST:event_ManageAirplaneBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ManageAirplaneBtn;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
