/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import TravelAgency.AirPlane;
import TravelAgency.Airliner;
import TravelAgency.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.ParseException;
import javax.swing.JPanel;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;

/**
 *
 * @author liumingyu
 */
public class ViewFlightJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightJpanel
     */
    private JPanel rightpanel;
    private Airliner airliner;
    private AirPlane airplane;
    private Flight flight;
    SimpleDateFormat ymd =   new SimpleDateFormat( "yyyy-MM-dd" );
    SimpleDateFormat hm =   new SimpleDateFormat( "HH:mm" );
    public ViewFlightJpanel(JPanel rightpanel,Airliner airliner,AirPlane airplane,Flight flight) {
        initComponents();
        this.rightpanel = rightpanel;
        this.airliner = airliner;
        this.airplane = airplane;
        
        
        
        NumberTxt.setText(String.valueOf(flight.getNum()));
        DateTxt.setText(ymd.format(flight.getDate()));
        DepatureTxt.setText(hm.format(flight.getDepaturetime()));
        FlightTimeTxt.setText(hm.format(flight.getTotaltime()));
        FromTxt.setText(flight.getFrom());
        ToTxt.setText(flight.getTo());
        NameTxt.setText(flight.getName());
        PriceTxt.setText(String.valueOf(flight.getPrice()));
        ArriveTxt.setText(hm.format(flight.getArrivetime()));
        
        NumberTxt.setEnabled(false);
        DateTxt.setEnabled(false);
        DepatureTxt.setEnabled(false);
        FlightTimeTxt.setEnabled(false);
        FromTxt.setEnabled(false);
        ToTxt.setEnabled(false);
        NameTxt.setEnabled(false);
        PriceTxt.setEnabled(false);
        ArriveTxt.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        NumberTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        DateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DepatureTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        FromTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ToTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        ArriveTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        FlightTimeTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        PriceTxt = new javax.swing.JTextField();
        BackBtn = new javax.swing.JButton();
        NameTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("View Flight");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(276, 6, 172, 48));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Flight Number:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 151, 129, 30));
        add(NumberTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 153, 135, -1));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Flight Date:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 199, 129, 30));
        add(DateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 201, 135, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Depature Time:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 105, 129, 30));
        add(DepatureTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 107, 135, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Flight From:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 247, 129, 30));
        add(FromTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 249, 135, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Flight To:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 295, 129, 30));
        add(ToTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 297, 135, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel7.setText("Arrive Time:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 153, 129, 30));
        add(ArriveTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 155, 135, -1));

        jLabel8.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel8.setText("Total Flight Time:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 201, 140, 30));
        add(FlightTimeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 203, 135, -1));

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel9.setText("Ticket Price:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(414, 249, 140, 30));
        add(PriceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 251, 135, -1));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back<<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(567, 396, 140, -1));
        add(NameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(186, 105, 135, -1));

        jLabel10.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel10.setText("Flight Name:");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(28, 103, 129, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        Component[] componentArray = rightpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        ManageFlightJpanel mfpanel = (ManageFlightJpanel) component;
        mfpanel.populate();
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_BackBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ArriveTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField DateTxt;
    private javax.swing.JTextField DepatureTxt;
    private javax.swing.JTextField FlightTimeTxt;
    private javax.swing.JTextField FromTxt;
    private javax.swing.JTextField NameTxt;
    private javax.swing.JTextField NumberTxt;
    private javax.swing.JTextField PriceTxt;
    private javax.swing.JTextField ToTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
