/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Airliner;

import TravelAgency.AirPlane;
import TravelAgency.AirPlaneDirectory;
import TravelAgency.Airliner;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liumingyu
 */
public class ViewPlaneJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPlaneJpanel
     */
    private JPanel airlinerpanel;
    private AirPlaneDirectory airpd;
    private AirPlane airplane;
    private Airliner airliner;
    public ViewPlaneJpanel(JPanel airlinerpanel,AirPlane airplane,Airliner airliner) {
        initComponents();
        this.airlinerpanel = airlinerpanel;
        this.airpd = airpd;
        this.airplane = airplane;
        this.airliner = airliner;
        
        Name.setText(airplane.getName());
        Seats.setText(String.valueOf(airplane.getAvailableseat()));
        AirlinerTxt.setText(airliner.getName());
        Type.setText(airplane.getModeltype());
        ID.setText(String.valueOf(airplane.getID()));
        
        Name.setEnabled(false);
        AirlinerTxt.setEnabled(false);
        Seats.setEnabled(false);
        Type.setEnabled(false);
        AirlinerTxt.setEnabled(false);
        ID.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BackBtn = new javax.swing.JButton();
        AirlinerTxt = new javax.swing.JTextField();
        Type = new javax.swing.JTextField();
        Name = new javax.swing.JTextField();
        Seats = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        UpdateBtn2 = new javax.swing.JButton();
        SaveBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        ID = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("View Plane");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 0, 176, 45));

        BackBtn.setBackground(new java.awt.Color(255, 255, 255));
        BackBtn.setText("Back<<");
        BackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackBtnActionPerformed(evt);
            }
        });
        add(BackBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 420, 111, -1));
        add(AirlinerTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 169, 165, 34));
        add(Type, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 116, 165, 34));

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 64, 165, 34));
        add(Seats, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 222, 165, 34));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Plane's Available Seats:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 221, 194, 34));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Plane Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 63, 181, 34));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Plane's Airliner:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 168, 194, 34));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Plane ModelType:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 116, 194, 34));

        UpdateBtn2.setBackground(new java.awt.Color(255, 255, 255));
        UpdateBtn2.setText("Update");
        UpdateBtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateBtn2ActionPerformed(evt);
            }
        });
        add(UpdateBtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 336, 125, -1));

        SaveBtn.setBackground(new java.awt.Color(255, 255, 255));
        SaveBtn.setText("Save");
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        add(SaveBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 336, 114, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("Plane's ID:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 275, 194, 30));
        add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(356, 274, 165, 34));
    }// </editor-fold>//GEN-END:initComponents

    private void BackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackBtnActionPerformed
        // TODO add your handling code here:
        airlinerpanel.remove(this);
        Component[] componentArray = airlinerpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        AirplaneJpanel apanel = (AirplaneJpanel) component;
        apanel.populate();
        CardLayout layout = (CardLayout) airlinerpanel.getLayout();
        layout.previous(airlinerpanel);
    }//GEN-LAST:event_BackBtnActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void UpdateBtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateBtn2ActionPerformed
        // TODO add your handling code here:
        
        Name.setEnabled(true);
        AirlinerTxt.setEnabled(true);
        Seats.setEnabled(true);
        Type.setEnabled(true);
        UpdateBtn2.setEnabled(false);
        SaveBtn.setEnabled(true);

    }//GEN-LAST:event_UpdateBtn2ActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed
        // TODO add your handling code here:
        airplane.setAvailableseat(Integer.parseInt(Seats.getText()));
        airplane.setModeltype(Type.getText());
        airplane.setName(Name.getText());
        airplane.setID(airplane.getID());
        Name.setEnabled(false);
        Type.setEnabled(false);
        AirlinerTxt.setEnabled(false);
        Seats.setEnabled(false);
        UpdateBtn2.setEnabled(true);
        SaveBtn.setEnabled(false);
        JOptionPane.showMessageDialog(null, "Account updated successfully");

    }//GEN-LAST:event_SaveBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField AirlinerTxt;
    private javax.swing.JButton BackBtn;
    private javax.swing.JTextField ID;
    private javax.swing.JTextField Name;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField Seats;
    private javax.swing.JTextField Type;
    private javax.swing.JButton UpdateBtn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    // End of variables declaration//GEN-END:variables
}
