/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.VitalSignHistory;
import javax.swing.JOptionPane;

/**
 *
 * @author liumingyu
 */
public class MainJframe extends javax.swing.JFrame {

    /**
     * Creates new form MainJframe
     */
    private VitalSignHistory vsh;
    public MainJframe() {
        initComponents();
        vsh = new VitalSignHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SplitPane = new javax.swing.JSplitPane();
        leftJpanel = new javax.swing.JPanel();
        CreateButton = new javax.swing.JButton();
        ViewBotton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        MaxTxt = new javax.swing.JTextField();
        MinTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        RightJpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        leftJpanel.setBackground(new java.awt.Color(255, 255, 255));

        CreateButton.setText("Create Vital Sign");
        CreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateButtonActionPerformed(evt);
            }
        });

        ViewBotton.setText("View Vital Sign");
        ViewBotton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewBottonActionPerformed(evt);
            }
        });

        jLabel1.setText("Max_BP");

        jLabel2.setText("Min_BP");

        MaxTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MaxTxtActionPerformed(evt);
            }
        });

        jButton1.setText("Abnormal");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftJpanelLayout = new javax.swing.GroupLayout(leftJpanel);
        leftJpanel.setLayout(leftJpanelLayout);
        leftJpanelLayout.setHorizontalGroup(
            leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpanelLayout.createSequentialGroup()
                .addGroup(leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(leftJpanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(MaxTxt)
                            .addComponent(MinTxt)))
                    .addGroup(leftJpanelLayout.createSequentialGroup()
                        .addGroup(leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CreateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(ViewBotton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        leftJpanelLayout.setVerticalGroup(
            leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftJpanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(CreateButton)
                .addGap(52, 52, 52)
                .addComponent(ViewBotton)
                .addGap(18, 18, 18)
                .addGroup(leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MaxTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(leftJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MinTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addComponent(jButton1)
                .addContainerGap(153, Short.MAX_VALUE))
        );

        SplitPane.setLeftComponent(leftJpanel);

        RightJpanel.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout RightJpanelLayout = new javax.swing.GroupLayout(RightJpanel);
        RightJpanel.setLayout(RightJpanelLayout);
        RightJpanelLayout.setHorizontalGroup(
            RightJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 581, Short.MAX_VALUE)
        );
        RightJpanelLayout.setVerticalGroup(
            RightJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        SplitPane.setRightComponent(RightJpanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(SplitPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(SplitPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateButtonActionPerformed
        // TODO add your handling code here:
        CreateVitalJpanel createJpanel = new CreateVitalJpanel(vsh);
        SplitPane.setRightComponent(createJpanel);
    }//GEN-LAST:event_CreateButtonActionPerformed

    private void ViewBottonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewBottonActionPerformed
        // TODO add your handling code here:V
        ViewVitalsJpanel viewpanel = new ViewVitalsJpanel(vsh);
        SplitPane.setRightComponent(viewpanel);
        
    }//GEN-LAST:event_ViewBottonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String maxbpString = MaxTxt.getText();
        String minbpString = MinTxt.getText();
        
        double maxbp;
        try{
            maxbp= maxbpString.equals("")?Double.MAX_VALUE:Double.parseDouble(maxbpString);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Wrong MAX_BP Type!");
            MaxTxt.setText("");
            MinTxt.setText("");
            return;
        }
        
        double minbp;
        try{
            minbp= minbpString.equals("")?Double.MIN_VALUE:Double.parseDouble(minbpString);
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, "Wrong MIN_BP Type!");
            MaxTxt.setText("");
            MinTxt.setText("");
            return;
        }
     
        AbnormalJpanel abnormaljpanel = new AbnormalJpanel(vsh, maxbp ,minbp);
        SplitPane.setRightComponent(abnormaljpanel);
        
        if(maxbp<minbp){
            JOptionPane.showMessageDialog(null, "Wrong Input! The MAX_BP must bigger than MIN_BP");
            MaxTxt.setText("");
            MinTxt.setText("");
        }
           
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void MaxTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MaxTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MaxTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJframe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJframe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CreateButton;
    private javax.swing.JTextField MaxTxt;
    private javax.swing.JTextField MinTxt;
    private javax.swing.JPanel RightJpanel;
    private javax.swing.JSplitPane SplitPane;
    private javax.swing.JButton ViewBotton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel leftJpanel;
    // End of variables declaration//GEN-END:variables
}
