/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import javax.swing.JOptionPane;
/**
 *
 * @author liumingyu
 */
public class AddressCreateJpanel extends javax.swing.JPanel {

    /**
     * Creates new form Adress
     */
    private Person person;
    public AddressCreateJpanel(Person person) {
        initComponents();
        this.person=person;
        
       
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Line2Txt = new javax.swing.JTextField();
        Line1Txt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        CreateAdressButton = new javax.swing.JButton();
        Citytxt = new javax.swing.JTextField();
        StateTxt = new javax.swing.JTextField();
        ZipCodeTxt = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "AddressCreate Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, null, new java.awt.Color(255, 204, 0)));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Line 2:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 170, 82, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel4.setText("City:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 82, -1));

        Line2Txt.setMinimumSize(new java.awt.Dimension(10, 28));
        Line2Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line2TxtActionPerformed(evt);
            }
        });
        add(Line2Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 170, 230, -1));

        Line1Txt.setMinimumSize(new java.awt.Dimension(10, 28));
        Line1Txt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line1TxtActionPerformed(evt);
            }
        });
        add(Line1Txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 230, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel7.setText("Zip Code:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 290, 90, -1));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Line 1:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 130, 82, -1));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel6.setText("State:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 82, -1));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 26)); // NOI18N
        jLabel1.setText("Create Address");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 60, 200, 34));

        CreateAdressButton.setBackground(new java.awt.Color(247, 251, 250));
        CreateAdressButton.setText("Create   Adress!");
        CreateAdressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateAdressButtonActionPerformed(evt);
            }
        });
        add(CreateAdressButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 380, 195, 23));

        Citytxt.setMinimumSize(new java.awt.Dimension(10, 28));
        Citytxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CitytxtActionPerformed(evt);
            }
        });
        add(Citytxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 230, 27));

        StateTxt.setMinimumSize(new java.awt.Dimension(10, 28));
        StateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateTxtActionPerformed(evt);
            }
        });
        add(StateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 250, 230, -1));

        ZipCodeTxt.setMinimumSize(new java.awt.Dimension(10, 28));
        ZipCodeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipCodeTxtActionPerformed(evt);
            }
        });
        add(ZipCodeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 290, 230, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void Line2TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line2TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line2TxtActionPerformed

    private void CreateAdressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateAdressButtonActionPerformed
        // TODO add your handling code here:
        person.getAddress().setStreetLine1(Line1Txt.getText());
        person.getAddress().setStreetLine2(Line2Txt.getText());
        person.getAddress().setCity(Citytxt.getText());
        person.getAddress().setState(StateTxt.getText());
        person.getAddress().setZipcode(ZipCodeTxt.getText());
        
          
System.out.println(person.getAddress().getZipcode());
        
        JOptionPane.showMessageDialog(null,"create Address Successfully");
    }//GEN-LAST:event_CreateAdressButtonActionPerformed

    private void CitytxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CitytxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CitytxtActionPerformed

    private void StateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateTxtActionPerformed

    private void ZipCodeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipCodeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipCodeTxtActionPerformed

    private void Line1TxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line1TxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line1TxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Citytxt;
    private javax.swing.JButton CreateAdressButton;
    private javax.swing.JTextField Line1Txt;
    private javax.swing.JTextField Line2Txt;
    private javax.swing.JTextField StateTxt;
    private javax.swing.JTextField ZipCodeTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
