/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import java.awt.Image;
import javax.swing.ImageIcon;

/**
 *
 * @author liumingyu
 */
public class DisplayJpanel extends javax.swing.JPanel {

    /**
     * Creates new form DisplayJpanel
     */    
    public DisplayJpanel(Person person) {
        initComponents();
        Display(person);
    }
    
    private void Display(Person person){
        String checkb = person.getAccount().getAccountbalance1();
        Checkbalance.setText(checkb);
        
        String saveb = person.getAccount().getAccountbalance2();
        Savingbalance.setText(saveb);
        
        String checkn = person.getAccount().getAccountnum1();
        checkNum.setText(checkn);
        
        String saven = person.getAccount().getAccountnum2();
        savingnumber.setText(saven);
        
       String checkingname = person.getAccount().getBankname1();
       checkname.setText(checkingname);
       
       String savename = person.getAccount().getBankname2();
       savingname.setText(savename);
       
       String ccode = person.getAccount().getSwiftcode1();
       checkcode.setText(ccode);
       
       String scode = person.getAccount().getSwiftcode2();
       savingcode.setText(scode);
       
       String city = person.getAddress().getCity();
       City.setText(city);
       
       String state = person.getAddress().getState();
       State.setText(state);
       
       String line1 = person.getAddress().getStreetLine1();
       Line1.setText(line1);
       
       String line2 = person.getAddress().getStreetLine2();
       Line2.setText(line2);
       
       String zipcode = person.getAddress().getZipcode();
       Zipcode.setText(zipcode);
       
       String casenum = person.getCases().getCasesnum();
       caseNumber.setText(casenum);
       
       String a1 = person.getCases().getAlergy1();
       Alergy1.setText(a1);
       
       String a2 = person.getCases().getAlergy2();
       Alergy2.setText(a2);
       
       String a3 = person.getCases().getAlergy3();
       Alergy3.setText(a3);      
       
       String age = person.getDemographic().getAge();
       Age.setText(age);
       
       String date = person.getDemographic().getBirthdate();
       DOB.setText(date);
       
       String firstname = person.getDemographic().getFirstname();
       Firstname.setText(firstname);
       
      String lastname = person.getDemographic().getLastname();
      Lastname.setText(lastname);
      
      String height = person.getDemographic().getHight();
      Height.setText(height);
      
      String weigh = person.getDemographic().getWeight();
      weight.setText(weigh);
      
      String ssn = person.getDemographic().getSsn();
      SSN.setText(ssn);
      
      String tel = person.getDemographic().getTelnum();
      Tel.setText(tel);
      
      String blood = person.getDriverlicense().getBloodtype();
      Blood.setText(blood);
      
      String pd =person.getDriverlicense().getPublicdate();
      PD.setText(pd);
      
      String vd = person.getDriverlicense().getValuedate();
      VD.setText(vd);
      
      String lnum =person.getDriverlicense().getLicensenum();
      licensenum.setText(lnum);
      
      ImageIcon icon = new ImageIcon(person.getDriverlicense().getPhoto());
        icon.setImage(icon.getImage().getScaledInstance(155, 155, Image.SCALE_DEFAULT));
        AttachPhoto.setIcon(icon);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        Firstname = new javax.swing.JTextField();
        Lastname = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        DOB = new javax.swing.JTextField();
        Age = new javax.swing.JTextField();
        Height = new javax.swing.JTextField();
        SSN = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        Line1 = new javax.swing.JTextField();
        Line2 = new javax.swing.JTextField();
        City = new javax.swing.JTextField();
        State = new javax.swing.JTextField();
        Alergy3 = new javax.swing.JTextField();
        licensenum = new javax.swing.JTextField();
        PD = new javax.swing.JTextField();
        VD = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Blood = new javax.swing.JTextField();
        AttachPhoto = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        checkNum = new javax.swing.JTextField();
        Checkbalance = new javax.swing.JTextField();
        checkcode = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        checkname = new javax.swing.JTextField();
        savingnumber = new javax.swing.JTextField();
        Savingbalance = new javax.swing.JTextField();
        savingcode = new javax.swing.JTextField();
        savingname = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        Zipcode = new javax.swing.JTextField();
        caseNumber = new javax.swing.JTextField();
        Alergy1 = new javax.swing.JTextField();
        Alergy2 = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "Display Panel         Display your Information!!!", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Nile", 0, 20), new java.awt.Color(255, 204, 0))); // NOI18N
        setMinimumSize(new java.awt.Dimension(540, 500));
        setPreferredSize(new java.awt.Dimension(500, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 310, 690, -1));

        jLabel2.setText("First Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 46, 107, 20));

        jLabel3.setText("Last Name:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 76, 107, 20));

        jLabel4.setText("TelNumber:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 107, 30));

        jLabel5.setText("DOB(dd/mm/yy):");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 136, -1, 20));

        jLabel6.setText("Age:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 166, 70, 20));

        jLabel7.setText("Height:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 196, 107, 20));

        jLabel8.setText("Height:");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 226, 107, 20));

        jLabel9.setText("SSN:");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 256, 107, 20));

        Firstname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstnameActionPerformed(evt);
            }
        });
        add(Firstname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 140, 30));

        Lastname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastnameActionPerformed(evt);
            }
        });
        add(Lastname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 140, 30));

        Tel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelActionPerformed(evt);
            }
        });
        add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 140, 30));

        DOB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DOBActionPerformed(evt);
            }
        });
        add(DOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 130, 140, 30));

        Age.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgeActionPerformed(evt);
            }
        });
        add(Age, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 160, 140, 30));

        Height.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HeightActionPerformed(evt);
            }
        });
        add(Height, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 140, 30));

        SSN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SSNActionPerformed(evt);
            }
        });
        add(SSN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 140, 30));

        jLabel10.setText("AddressLine1：");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 46, -1, 20));

        jLabel11.setText("AddressLine2：");
        add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 76, -1, 20));

        jLabel12.setText("City:");
        add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 106, 98, 20));

        jLabel13.setText("State:");
        add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 136, 98, 20));

        jLabel14.setText("ZipCode:");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 166, 98, 20));

        jLabel15.setText("License Num:");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, 30));

        jLabel16.setText("Public Date:");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 370, 85, 30));

        jLabel17.setText("Value Date:");
        add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 400, 85, 30));

        Line1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line1ActionPerformed(evt);
            }
        });
        add(Line1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 40, 140, 30));

        Line2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Line2ActionPerformed(evt);
            }
        });
        add(Line2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 140, 30));

        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        add(City, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 100, 140, 30));

        State.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StateActionPerformed(evt);
            }
        });
        add(State, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 130, 140, 30));

        Alergy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy3ActionPerformed(evt);
            }
        });
        add(Alergy3, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 280, 140, 30));

        licensenum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                licensenumActionPerformed(evt);
            }
        });
        add(licensenum, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 340, 140, 30));

        PD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PDActionPerformed(evt);
            }
        });
        add(PD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 370, 140, 30));

        VD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VDActionPerformed(evt);
            }
        });
        add(VD, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 400, 140, 30));

        jLabel18.setText("Blood Type:");
        add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 286, -1, 20));

        jLabel19.setText("License Photo:");
        add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 450, -1, -1));

        Blood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodActionPerformed(evt);
            }
        });
        add(Blood, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 280, 140, 30));
        add(AttachPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 450, 150, 140));

        jLabel20.setForeground(new java.awt.Color(255, 153, 0));
        jLabel20.setText("Saving Account:");
        add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 120, 30));

        jLabel21.setText("Account Number:");
        add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 340, -1, 20));

        jLabel22.setText("Account Balance:");
        add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 370, 110, 20));

        jLabel23.setText("Swift Code:");
        add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 110, 20));

        jLabel24.setText("Bank Name:");
        add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 430, 110, 30));

        jLabel25.setForeground(new java.awt.Color(255, 153, 0));
        jLabel25.setText("Checking Account:");
        add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 142, -1));

        jLabel26.setText("Account Number:");
        add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 470, -1, 30));

        jLabel27.setText("Account Balance:");
        add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 110, 30));

        jLabel28.setText("Swift Code:");
        add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 530, -1, 30));

        jLabel29.setText("Bank Name:");
        add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 560, -1, 30));

        checkNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkNumActionPerformed(evt);
            }
        });
        add(checkNum, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 140, -1));

        Checkbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckbalanceActionPerformed(evt);
            }
        });
        add(Checkbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 140, -1));

        checkcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkcodeActionPerformed(evt);
            }
        });
        add(checkcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 400, 140, -1));

        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 140, 30));

        checkname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checknameActionPerformed(evt);
            }
        });
        add(checkname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 140, -1));

        savingnumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingnumberActionPerformed(evt);
            }
        });
        add(savingnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 470, 140, -1));

        Savingbalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SavingbalanceActionPerformed(evt);
            }
        });
        add(Savingbalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 500, 140, -1));

        savingcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingcodeActionPerformed(evt);
            }
        });
        add(savingcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 530, 140, -1));

        savingname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savingnameActionPerformed(evt);
            }
        });
        add(savingname, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 560, 140, -1));

        jLabel30.setText("CaseNumber:");
        add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 196, 98, 20));

        jLabel31.setText("Alergy1:");
        add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 226, 98, 20));

        jLabel32.setText("Alergy2:");
        add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 256, 98, 20));

        jLabel33.setText("Alergy3:");
        add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 286, 98, 20));

        Zipcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZipcodeActionPerformed(evt);
            }
        });
        add(Zipcode, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 160, 140, 30));

        caseNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caseNumberActionPerformed(evt);
            }
        });
        add(caseNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 190, 140, 30));

        Alergy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy1ActionPerformed(evt);
            }
        });
        add(Alergy1, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 220, 140, 30));

        Alergy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Alergy2ActionPerformed(evt);
            }
        });
        add(Alergy2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 250, 140, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void FirstnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FirstnameActionPerformed

    private void LastnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastnameActionPerformed

    private void TelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelActionPerformed

    private void DOBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DOBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DOBActionPerformed

    private void AgeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AgeActionPerformed

    private void HeightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HeightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HeightActionPerformed

    private void SSNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SSNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SSNActionPerformed

    private void Line1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line1ActionPerformed

    private void Line2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Line2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Line2ActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void StateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StateActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StateActionPerformed

    private void Alergy3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy3ActionPerformed

    private void licensenumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_licensenumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_licensenumActionPerformed

    private void PDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PDActionPerformed

    private void VDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_VDActionPerformed

    private void BloodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodActionPerformed

    private void checkNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkNumActionPerformed

    private void CheckbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CheckbalanceActionPerformed

    private void checkcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkcodeActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void checknameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checknameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checknameActionPerformed

    private void savingnumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingnumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingnumberActionPerformed

    private void SavingbalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SavingbalanceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SavingbalanceActionPerformed

    private void savingcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingcodeActionPerformed

    private void savingnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savingnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_savingnameActionPerformed

    private void ZipcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZipcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ZipcodeActionPerformed

    private void caseNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caseNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caseNumberActionPerformed

    private void Alergy1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy1ActionPerformed

    private void Alergy2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Alergy2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Alergy2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Age;
    private javax.swing.JTextField Alergy1;
    private javax.swing.JTextField Alergy2;
    private javax.swing.JTextField Alergy3;
    private javax.swing.JLabel AttachPhoto;
    private javax.swing.JTextField Blood;
    private javax.swing.JTextField Checkbalance;
    private javax.swing.JTextField City;
    private javax.swing.JTextField DOB;
    private javax.swing.JTextField Firstname;
    private javax.swing.JTextField Height;
    private javax.swing.JTextField Lastname;
    private javax.swing.JTextField Line1;
    private javax.swing.JTextField Line2;
    private javax.swing.JTextField PD;
    private javax.swing.JTextField SSN;
    private javax.swing.JTextField Savingbalance;
    private javax.swing.JTextField State;
    private javax.swing.JTextField Tel;
    private javax.swing.JTextField VD;
    private javax.swing.JTextField Zipcode;
    private javax.swing.JTextField caseNumber;
    private javax.swing.JTextField checkNum;
    private javax.swing.JTextField checkcode;
    private javax.swing.JTextField checkname;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField licensenum;
    private javax.swing.JTextField savingcode;
    private javax.swing.JTextField savingname;
    private javax.swing.JTextField savingnumber;
    private javax.swing.JTextField weight;
    // End of variables declaration//GEN-END:variables
}
