/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Person;
import java.awt.Image;
import java.io.File;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author liumingyu
 */
public class DriverCreateJpanel extends javax.swing.JPanel {

    /**
     * Creates new form DriverCreateJpanel
     */
    private Person person;
    public DriverCreateJpanel(Person person) {
        initComponents();
        this.person=person;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel6 = new javax.swing.JLabel();
        ValueDateTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CreateLIcenseButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        PublicDateTxt = new javax.swing.JTextField();
        LicenseNumTxt = new javax.swing.JTextField();
        LicensePhoto = new javax.swing.JTextField();
        BloodTypeTxt = new javax.swing.JTextField();
        choosefileButton = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)), "DriverLicenseCreate Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Al Bayan", 0, 20), new java.awt.Color(255, 204, 0))); // NOI18N
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel6.setText("Blood Type:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, 202, 30));

        ValueDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValueDateTxtActionPerformed(evt);
            }
        });
        add(ValueDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 250, -1));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel4.setText("Value Date(mm/yy):");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 202, 43));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel2.setText("License Number:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 202, 43));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel3.setText("Public Date(mm/yy):");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 170, 202, 47));

        CreateLIcenseButton.setBackground(new java.awt.Color(247, 251, 250));
        CreateLIcenseButton.setText("Create   Driver's License!");
        CreateLIcenseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreateLIcenseButtonActionPerformed(evt);
            }
        });
        add(CreateLIcenseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 400, 264, -1));

        jLabel7.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        jLabel7.setText("License Photo:");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 340, 202, 26));

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 24)); // NOI18N
        jLabel1.setText("Create Driver's License");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, -1, 42));

        PublicDateTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PublicDateTxtActionPerformed(evt);
            }
        });
        add(PublicDateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, 250, -1));
        add(LicenseNumTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 250, -1));

        LicensePhoto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LicensePhotoActionPerformed(evt);
            }
        });
        add(LicensePhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 340, 250, -1));

        BloodTypeTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BloodTypeTxtActionPerformed(evt);
            }
        });
        add(BloodTypeTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 290, 250, -1));

        choosefileButton.setBackground(new java.awt.Color(247, 251, 250));
        choosefileButton.setText("choose file");
        choosefileButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                choosefileButtonActionPerformed(evt);
            }
        });
        add(choosefileButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 340, 100, -1));
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 370, 120, 100));
    }// </editor-fold>//GEN-END:initComponents

    private void ValueDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValueDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValueDateTxtActionPerformed

    private void CreateLIcenseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreateLIcenseButtonActionPerformed
        // TODO add your handling code here:
        person.getDriverlicense().setBloodtype(BloodTypeTxt.getText());
        person.getDriverlicense().setLicensenum(LicenseNumTxt.getText());
        person.getDriverlicense().setPublicdate(PublicDateTxt.getText());
        person.getDriverlicense().setValuedate(ValueDateTxt.getText());
        
        JOptionPane.showMessageDialog(null,"create Address Successfully");
    }//GEN-LAST:event_CreateLIcenseButtonActionPerformed

    private void PublicDateTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PublicDateTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PublicDateTxtActionPerformed

    private void LicensePhotoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LicensePhotoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LicensePhotoActionPerformed

    private void BloodTypeTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BloodTypeTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BloodTypeTxtActionPerformed

    private void choosefileButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_choosefileButtonActionPerformed
        // TODO add your handling code here:
        
        JFileChooser photo = new JFileChooser();
        photo.setFileSelectionMode(JFileChooser.FILES_ONLY);
        photo.showOpenDialog(null);
        File f = photo.getSelectedFile();
        String filename = f.getAbsolutePath();
        LicensePhoto.setText(filename);
        
        person.getDriverlicense().setPhoto(filename);
        
        ImageIcon icon = new ImageIcon(filename);
        icon.setImage(icon.getImage().getScaledInstance(155, 155, Image.SCALE_DEFAULT));
        jLabel5.setIcon(icon);      
        
    }//GEN-LAST:event_choosefileButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BloodTypeTxt;
    private javax.swing.JButton CreateLIcenseButton;
    private javax.swing.JTextField LicenseNumTxt;
    private javax.swing.JTextField LicensePhoto;
    private javax.swing.JTextField PublicDateTxt;
    private javax.swing.JTextField ValueDateTxt;
    private javax.swing.JButton choosefileButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
