/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
//import Business.Person;
import Business.Address;
import Business.Person;
import Business.Cases;
import Business.Account;
import Business.DriverLicense;
import Business.Demographic;


/**
 *
 * @author liumingyu
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    
    private Address address;
    private Person person;
    private Cases cases;
    private Account account;
    private DriverLicense driverlicense;
    private Demographic demographic;
    
    public MainJFrame() {
        initComponents();
        
        person=new Person();
        
        address =new Address();
        person.setAddress(address);
        
        cases = new Cases();
        person.setCases(cases);
        
        account = new Account();
        person.setAccount(account);
        
        driverlicense = new DriverLicense();
        person.setDriverlicense(driverlicense);
        
        demographic = new Demographic();
        person.setDemographic(demographic);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Splitpane = new javax.swing.JSplitPane();
        ControlJpanel = new javax.swing.JPanel();
        Person_Info = new javax.swing.JLabel();
        PersonCreateButton = new javax.swing.JButton();
        PersonViewButton = new javax.swing.JButton();
        Adress_Info = new javax.swing.JLabel();
        AdressCreateButton = new javax.swing.JButton();
        AdressViewButton = new javax.swing.JButton();
        CheckingAccount = new javax.swing.JLabel();
        AccountCreateButton = new javax.swing.JButton();
        AccountViewButton = new javax.swing.JButton();
        DriverLIcense_Info = new javax.swing.JLabel();
        DriverCreateButton = new javax.swing.JButton();
        DriverViewButton = new javax.swing.JButton();
        Cases_Info = new javax.swing.JLabel();
        CasesCreateButton = new javax.swing.JButton();
        CasesViewButton = new javax.swing.JButton();
        Final_Display = new javax.swing.JLabel();
        DisplayButton = new javax.swing.JButton();
        DisplayJpanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 650));

        Splitpane.setBackground(new java.awt.Color(255, 255, 255));
        Splitpane.setPreferredSize(new java.awt.Dimension(500, 554));

        ControlJpanel.setBackground(new java.awt.Color(255, 255, 255));
        ControlJpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true), "Control Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 0, 20), new java.awt.Color(255, 204, 0))); // NOI18N
        ControlJpanel.setToolTipText("");
        ControlJpanel.setPreferredSize(new java.awt.Dimension(200, 300));
        ControlJpanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Person_Info.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 13)); // NOI18N
        Person_Info.setText(" Demographic   INFO");
        ControlJpanel.add(Person_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 138, -1));

        PersonCreateButton.setBackground(new java.awt.Color(247, 251, 250));
        PersonCreateButton.setText("Create");
        PersonCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonCreateButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(PersonCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 66, -1));

        PersonViewButton.setBackground(new java.awt.Color(247, 251, 250));
        PersonViewButton.setText("View");
        PersonViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PersonViewButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(PersonViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 66, -1));

        Adress_Info.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 13)); // NOI18N
        Adress_Info.setText("    Adress   INFO");
        ControlJpanel.add(Adress_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, 120, -1));

        AdressCreateButton.setBackground(new java.awt.Color(247, 251, 250));
        AdressCreateButton.setText("Create");
        AdressCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdressCreateButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(AdressCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 180, 66, -1));

        AdressViewButton.setBackground(new java.awt.Color(247, 251, 250));
        AdressViewButton.setText("View");
        AdressViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdressViewButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(AdressViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 66, -1));

        CheckingAccount.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 13)); // NOI18N
        CheckingAccount.setText("    Account   INFO");
        ControlJpanel.add(CheckingAccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 120, -1));

        AccountCreateButton.setBackground(new java.awt.Color(247, 251, 250));
        AccountCreateButton.setText("Create");
        AccountCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountCreateButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(AccountCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 260, 66, -1));

        AccountViewButton.setBackground(new java.awt.Color(247, 251, 250));
        AccountViewButton.setText("View");
        AccountViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AccountViewButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(AccountViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 66, -1));

        DriverLIcense_Info.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 13)); // NOI18N
        DriverLIcense_Info.setText("    DriverLicense INFO");
        ControlJpanel.add(DriverLIcense_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 310, 137, 27));

        DriverCreateButton.setBackground(new java.awt.Color(247, 251, 250));
        DriverCreateButton.setText("Create");
        DriverCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverCreateButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(DriverCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 340, 68, -1));

        DriverViewButton.setBackground(new java.awt.Color(247, 251, 250));
        DriverViewButton.setText("View");
        DriverViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DriverViewButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(DriverViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 64, -1));

        Cases_Info.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 13)); // NOI18N
        Cases_Info.setText("      Cases     INFO");
        ControlJpanel.add(Cases_Info, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 133, 20));

        CasesCreateButton.setBackground(new java.awt.Color(247, 251, 250));
        CasesCreateButton.setText("Create");
        CasesCreateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasesCreateButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(CasesCreateButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 420, 68, -1));

        CasesViewButton.setBackground(new java.awt.Color(247, 251, 250));
        CasesViewButton.setText("View");
        CasesViewButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CasesViewButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(CasesViewButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 420, 63, -1));

        Final_Display.setFont(new java.awt.Font("Plantagenet Cherokee", 0, 13)); // NOI18N
        Final_Display.setText("     Final   Display");
        ControlJpanel.add(Final_Display, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 460, 130, 20));

        DisplayButton.setBackground(new java.awt.Color(247, 251, 250));
        DisplayButton.setText("Display!");
        DisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButtonActionPerformed(evt);
            }
        });
        ControlJpanel.add(DisplayButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 490, 140, -1));

        Splitpane.setLeftComponent(ControlJpanel);

        DisplayJpanel.setBackground(new java.awt.Color(255, 255, 255));
        DisplayJpanel.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 204, 0), 1, true), "Display Panel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("American Typewriter", 0, 20), new java.awt.Color(255, 204, 0))); // NOI18N
        DisplayJpanel.setForeground(new java.awt.Color(255, 204, 51));
        DisplayJpanel.setPreferredSize(new java.awt.Dimension(500, 550));

        javax.swing.GroupLayout DisplayJpanelLayout = new javax.swing.GroupLayout(DisplayJpanel);
        DisplayJpanel.setLayout(DisplayJpanelLayout);
        DisplayJpanelLayout.setHorizontalGroup(
            DisplayJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 504, Short.MAX_VALUE)
        );
        DisplayJpanelLayout.setVerticalGroup(
            DisplayJpanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );

        Splitpane.setRightComponent(DisplayJpanel);

        getContentPane().add(Splitpane, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PersonCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonCreateButtonActionPerformed
        // TODO add your handling code here:
        DemographicCreateJpanel demographiccreatejpanel = new DemographicCreateJpanel(person);
        Splitpane.setRightComponent(demographiccreatejpanel);
        
    }//GEN-LAST:event_PersonCreateButtonActionPerformed

    private void PersonViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PersonViewButtonActionPerformed
        // TODO add your handling code here:
        DemographicViewJpanel demographicviewjpanel = new DemographicViewJpanel(person);
        Splitpane.setRightComponent(demographicviewjpanel);
    }//GEN-LAST:event_PersonViewButtonActionPerformed

    private void AdressCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdressCreateButtonActionPerformed
        // TODO add your handling code here:
        AddressCreateJpanel addresscreatejpanel = new AddressCreateJpanel(person);
        Splitpane.setRightComponent(addresscreatejpanel);
        //SplitPane.setRightComponent(createjpanel);
    }//GEN-LAST:event_AdressCreateButtonActionPerformed

    private void AdressViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdressViewButtonActionPerformed
        // TODO add your handling code here:
        AddressViewJpanel addressviewjpanel = new AddressViewJpanel(person);
        Splitpane.setRightComponent(addressviewjpanel);
    }//GEN-LAST:event_AdressViewButtonActionPerformed

    private void AccountCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountCreateButtonActionPerformed
        // TODO add your handling code here:
        AccountCreateJpanel accountcreatejpanel = new AccountCreateJpanel(person);
        Splitpane.setRightComponent(accountcreatejpanel);
    }//GEN-LAST:event_AccountCreateButtonActionPerformed

    private void AccountViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AccountViewButtonActionPerformed
        // TODO add your handling code here:
        AccountViewJpanel accountviewjpanel = new AccountViewJpanel(person);
        Splitpane.setRightComponent(accountviewjpanel);
    }//GEN-LAST:event_AccountViewButtonActionPerformed

    private void DriverCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverCreateButtonActionPerformed
        // TODO add your handling code here:
        DriverCreateJpanel drivercreatejpanel = new DriverCreateJpanel(person);
        Splitpane.setRightComponent(drivercreatejpanel);
    }//GEN-LAST:event_DriverCreateButtonActionPerformed

    private void DriverViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DriverViewButtonActionPerformed
        // TODO add your handling code here:
        DriverViewJpanel driverviewjpanel = new DriverViewJpanel(person);
        Splitpane.setRightComponent(driverviewjpanel);
        
   
    }//GEN-LAST:event_DriverViewButtonActionPerformed

    private void CasesCreateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasesCreateButtonActionPerformed
        // TODO add your handling code here:
        CasesCreateJpanel casescreatejpanel = new CasesCreateJpanel(person);
        Splitpane.setRightComponent(casescreatejpanel);
    }//GEN-LAST:event_CasesCreateButtonActionPerformed

    private void CasesViewButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CasesViewButtonActionPerformed
        // TODO add your handling code here:
        CasesViewJpanel caseviewjpanel = new CasesViewJpanel(person);
        Splitpane.setRightComponent(caseviewjpanel);
        
    }//GEN-LAST:event_CasesViewButtonActionPerformed

    private void DisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButtonActionPerformed
        // TODO add your handling code here:
        DisplayJpanel displayjpanel = new DisplayJpanel(person);
        Splitpane.setRightComponent(displayjpanel);
        
    }//GEN-LAST:event_DisplayButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AccountCreateButton;
    private javax.swing.JButton AccountViewButton;
    private javax.swing.JButton AdressCreateButton;
    private javax.swing.JButton AdressViewButton;
    private javax.swing.JLabel Adress_Info;
    private javax.swing.JButton CasesCreateButton;
    private javax.swing.JButton CasesViewButton;
    private javax.swing.JLabel Cases_Info;
    private javax.swing.JLabel CheckingAccount;
    private javax.swing.JPanel ControlJpanel;
    private javax.swing.JButton DisplayButton;
    private javax.swing.JPanel DisplayJpanel;
    private javax.swing.JButton DriverCreateButton;
    private javax.swing.JLabel DriverLIcense_Info;
    private javax.swing.JButton DriverViewButton;
    private javax.swing.JLabel Final_Display;
    private javax.swing.JButton PersonCreateButton;
    private javax.swing.JButton PersonViewButton;
    private javax.swing.JLabel Person_Info;
    private javax.swing.JSplitPane Splitpane;
    // End of variables declaration//GEN-END:variables
}
