/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.TravelAgency;

import TravelAgency.AirPlane;
import TravelAgency.Airliner;
import TravelAgency.AirlinerDirectory;
import TravelAgency.Flight;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class ViewFlightJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewFlightJpanel
     */
    private JPanel rightpanel;
    private AirlinerDirectory aird;
    public ViewFlightJpanel(JPanel rightpanel,AirlinerDirectory aird) {
        initComponents();
        this.aird = aird;
        this.rightpanel = rightpanel;
        populate();
    }
    public void populate(){
        int rowCount = FlightTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)FlightTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        for(Airliner al : aird.getAirlinerDirectory()){
            for(AirPlane ap : al.getAirplanedirectory().getAirplanedirectory()){
                for(Flight f  : ap.getFlightDirectory().getFlightdirectory()){
                    SimpleDateFormat ymd = new SimpleDateFormat( "yyyy-MM-dd" );
                    SimpleDateFormat hm = new SimpleDateFormat( "HH:mm" );
                    
                    Object row[] = new Object[dtm.getColumnCount()];
                    row[0] = f;
                    row[1] = al.getName();
                    row[2] = ymd.format(f.getDate());
                    row[3] = hm.format(f.getDepaturetime());
                    row[4] = f.getFrom();
                    row[5] = f.getTo();
                    row[6] = f.getPrice();
                    
            
            dtm.addRow(row);
                }
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        Backbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Airliner Name", "Depature Date", "Depature Time", "From", "To", "Price"
            }
        ));
        jScrollPane1.setViewportView(FlightTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 691, 281));

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("View All Flight");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 10, 210, 50));

        Backbtn.setBackground(new java.awt.Color(255, 255, 255));
        Backbtn.setText("Back<<");
        Backbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackbtnActionPerformed(evt);
            }
        });
        add(Backbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 440, 114, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void BackbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackbtnActionPerformed
        // TODO add your handling code here:
        this.rightpanel.remove(this);
        CardLayout cardlayout =  (CardLayout)this.rightpanel.getLayout();
        Component[] comps = this.rightpanel.getComponents();

        for(Component comp : comps){
            if(comp instanceof ManageAirliner){
                ManageAirliner maPanel = (ManageAirliner)comp;
                maPanel.populate();
            }
        }

        cardlayout.previous(rightpanel);
    }//GEN-LAST:event_BackbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Backbtn;
    private javax.swing.JTable FlightTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
