/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import TravelAgency.Airliner;
import TravelAgency.AirlinerDirectory;
import TravelAgency.Customer;
import TravelAgency.Flight;
import TravelAgency.Order;
import java.awt.CardLayout;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class BookingJpanel extends javax.swing.JPanel {

    /**
     * Creates new form BookingJpanel
     */
    private JPanel rightpanel;
    private Customer customer;
    private Flight flight;
    private AirlinerDirectory aird;
    public BookingJpanel(JPanel rightpanel,Customer customer,Flight flight) {
        initComponents();
        this.rightpanel = rightpanel;
        this.customer = customer;
        this.flight = flight;
        control();
        populate();
        
        txtfltNum.setText(String.valueOf(flight.getNum()));
        txtRemainSeat.setText(String.valueOf(flight.getSeatlist().getRemainSeat()));
        System.out.print(customer);
    }

    
    public void control(){
        int[][] arr = flight.getSeatlist().getArrSeat();
       
        DefaultTableModel dtm = (DefaultTableModel)tblSeat.getModel();
        dtm.setRowCount(0);
       
        for(int a=0;a<arr.length;a++){//控制每个一维数组
            
                       String[] ar = new String [7];
                        
			for(int i=0;i<arr[a].length;i++){//控制每个一维数组中的元素
				if(arr[a][i] == 1){
                                ar[6] = (String.valueOf(a+1));
                                ar[i] = "Booked";
                                }else{
                                ar[6] = (String.valueOf(a+1));    
                                }
			}
                        
                        dtm.addRow(ar);//每执行完一个一维数组换行
		}
    }
    
    
    public void populate(){
        
        
        
        rowComboBox.removeAllItems();
        columnComboBox.removeAllItems();
        
        int sum = 0;
        int[][] arr1 = flight.getSeatlist().getArrSeat();
        for (int a=0; a<arr1.length; a++){
            for(int i=0; i<arr1[a].length; i++){
               sum  = sum + arr1[a][i];
            }
            if(sum != 25){
                   sum =0;
                   rowComboBox.addItem(a+1);        
            }
        }
    
    
        int sum1 = 0;
       
        int row = rowComboBox.getSelectedIndex();
        if(sum1 != 6){
            for(int a=0;a<arr1.length; a++){
                sum1 = sum1 + arr1[a][0];
            }
            columnComboBox.addItem("A"); 
            sum1 = 0;
        }
        
        if(sum1 != 6){
            for(int a=0;a<arr1.length; a++){
                sum1 = sum1 + arr1[a][1];
            }
            columnComboBox.addItem("B"); 
            sum1 = 0;
        }
            
        if(sum1 != 6){
            for(int a=0;a<arr1.length; a++){
                sum1 = sum1 + arr1[a][2];
            }
            columnComboBox.addItem("C"); 
            sum1 = 0;
        } 
        
        if(sum1 != 6){
            for(int a=0;a<arr1.length; a++){
                sum1 = sum1 + arr1[a][3];
            }
            columnComboBox.addItem("D"); 
            sum1 = 0;
        }   
        
        if(sum1 != 6){
            for(int a=0;a<arr1.length; a++){
                sum1 = sum1 + arr1[a][4];
            }
            columnComboBox.addItem("E"); 
            sum1 = 0;
        }   
        
        if(sum1 != 6){
            for(int a=0;a<arr1.length; a++){
                sum1 = sum1 + arr1[a][5];
            }
            columnComboBox.addItem("F"); 
            sum1 = 0;
        }   
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        btnBook = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        txtfltNum = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtRemainSeat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        columnComboBox = new javax.swing.JComboBox();
        rowComboBox = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSeat = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        SelectedTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));

        jLabel3.setText("Seat Remianing:");

        btnBook.setText("Book");
        btnBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBookActionPerformed(evt);
            }
        });

        jLabel2.setText("Flight Number:");

        btnBack.setText("Back<<");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        jLabel5.setText("Column:");

        txtfltNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtfltNumActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel4.setText("Select your Seat");

        jLabel6.setText("Row:");

        columnComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {}));
        columnComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                columnComboBoxActionPerformed(evt);
            }
        });

        rowComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] {  }));
        rowComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rowComboBoxActionPerformed(evt);
            }
        });

        jLabel1.setText("Select your Seat:");

        tblSeat.setBackground(new java.awt.Color(255, 204, 204));
        tblSeat.setFont(new java.awt.Font("Malayalam MN", 1, 12)); // NOI18N
        tblSeat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, "01"},
                {null, null, null, null, null, null, "02"},
                {null, null, null, null, null, null, "03"},
                {null, null, null, null, null, null, "04"},
                {null, null, null, null, null, null, "05"},
                {null, null, null, null, null, null, "06"},
                {null, null, null, null, null, null, "07"},
                {null, null, null, null, null, null, "08"},
                {null, null, null, null, null, null, "09"},
                {null, null, null, null, null, null, "10"},
                {null, null, null, null, null, null, "11"},
                {null, null, null, null, null, null, "12"},
                {null, null, null, null, null, null, "13"},
                {null, null, null, null, null, null, "14"},
                {null, null, null, null, null, null, "15"},
                {null, null, null, null, null, null, "16"},
                {null, null, null, null, null, null, "17"},
                {null, null, null, null, null, null, "18"},
                {null, null, null, null, null, null, "19"},
                {null, null, null, null, null, null, "20"},
                {null, null, null, null, null, null, "21"},
                {null, null, null, null, null, null, "22"},
                {null, null, null, null, null, null, "23"},
                {null, null, null, null, null, null, "24"},
                {null, null, null, null, null, null, "25"}
            },
            new String [] {
                "A(Left)", "B(Left)", "C(Middle)", "D(Middle)", "E(Right)", "F(Right)", ""
            }
        ));
        jScrollPane2.setViewportView(tblSeat);
        if (tblSeat.getColumnModel().getColumnCount() > 0) {
            tblSeat.getColumnModel().getColumn(6).setPreferredWidth(30);
        }

        jLabel7.setText("You Selected:");

        SelectedTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SelectedTxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Position:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 430, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(328, 328, 328))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel6)
                            .addGap(378, 378, 378)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(12, 12, 12)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(17, 17, 17))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnBook, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(16, 16, 16)
                                .addComponent(SelectedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(rowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jLabel2)
                        .addGap(60, 60, 60)
                        .addComponent(txtfltNum, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jLabel3)
                        .addGap(53, 53, 53)
                        .addComponent(txtRemainSeat, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel2))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtfltNum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3)
                        .addComponent(txtRemainSeat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(columnComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(rowComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40)
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(SelectedTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addGap(84, 84, 84)
                        .addComponent(btnBook)
                        .addGap(63, 63, 63)
                        .addComponent(btnBack))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(48, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBookActionPerformed
        // TODO add your handling code here:

        int[][] arr = flight.getSeatlist().getArrSeat();
        if(arr[rowComboBox.getSelectedIndex()][columnComboBox.getSelectedIndex()] == 1){
            JOptionPane.showMessageDialog(null,"The seat has been booked.");
            return;
        }
        Order order = customer.getOrderdirectory().addOrder();
        order.setCustomer(customer);
        order.setFlight(flight);
        order.setSeat(rowComboBox.getSelectedIndex(), columnComboBox.getSelectedIndex(),(String)columnComboBox.getSelectedItem());

        int r = order.getFlight().getSeatlist().getRemainSeat();
        r = r-1;

        order.setOrderNum("1");

        
        order.getFlight().getSeatlist().setArrSeatValue(rowComboBox.getSelectedIndex(), columnComboBox.getSelectedIndex(), 1);

        JOptionPane.showMessageDialog(null, "Order Created Successfully");
        System.out.println(r);
        System.out.println();
        control();

        for(int a=0;a<arr.length;a++){//控制每个一维数组
            for(int i=0;i<arr[a].length;i++){//控制每个一维数组中的元素
                System.out.print(arr[a][i]+" ");//输出每个元素的值
            }
            System.out.println();//每执行完一个一维数组换行
        }
        
        order.getFlight().getSeatlist().setRemainSeat(r);
        txtRemainSeat.setText(String.valueOf(flight.getSeatlist().getRemainSeat()));
        System.out.print(r);
        
        SelectedTxt.setText(String.valueOf(columnComboBox.getSelectedItem())+String.valueOf(rowComboBox.getSelectedItem()));
        order.getSeat().setSeatPosition(String.valueOf(columnComboBox.getSelectedItem())+String.valueOf(rowComboBox.getSelectedItem()));
        
        

    }//GEN-LAST:event_btnBookActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        rightpanel.remove(this);
        Component[] componentArray = rightpanel.getComponents();
        Component component = componentArray[componentArray.length - 1];
        SearchFlightJpanel searchpanel = (SearchFlightJpanel) component;
        CardLayout layout = (CardLayout) rightpanel.getLayout();
        layout.previous(rightpanel);
    }//GEN-LAST:event_btnBackActionPerformed

    private void txtfltNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtfltNumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtfltNumActionPerformed

    private void columnComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_columnComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_columnComboBoxActionPerformed

    private void rowComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rowComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rowComboBoxActionPerformed

    private void SelectedTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectedTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectedTxtActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField SelectedTxt;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnBook;
    private javax.swing.JComboBox columnComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JComboBox rowComboBox;
    private javax.swing.JTable tblSeat;
    private javax.swing.JTextField txtRemainSeat;
    private javax.swing.JTextField txtfltNum;
    // End of variables declaration//GEN-END:variables
}
