/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import TravelAgency.AirPlane;
import TravelAgency.AirPlaneDirectory;
import TravelAgency.Airliner;
import TravelAgency.AirlinerDirectory;
import TravelAgency.Customer;
import TravelAgency.CustomerDirectory;
import TravelAgency.Flight;
import TravelAgency.FlightDirectory;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author liumingyu
 */
public class CustomerLoginJpanel extends javax.swing.JPanel {

    /**
     * Creates new form CustomerLoginJpanel
     */
    private JPanel rightpanel;
    private FlightDirectory fld;
    CustomerDirectory csdirectory;
    private AirlinerDirectory airdir;
    private Flight fl;
    private AirPlane airp;
    private Airliner airliner;
    private AirPlaneDirectory airpd;
    private AirPlane airplane;
    private Customer customer;
    public CustomerLoginJpanel(JPanel rightpanel,CustomerDirectory csdir,FlightDirectory fld,AirlinerDirectory airdir,Customer customer) {
        initComponents();
        this.fld = fld;
        this.rightpanel = rightpanel;
        this.airdir = airdir;
        this.csdirectory = csdir;
        this.customer = customer;
        populate();
        System.out.print(customer);
        
    }
    public void populate(){
        
        
        
        customerComboBox.removeAllItems();
        for (Customer cust :csdirectory.getCustomerdirectory() ){
            customerComboBox.addItem(cust);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        Tel = new javax.swing.JTextField();
        Email = new javax.swing.JTextField();
        Birth = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        btnCreate = new javax.swing.JButton();
        customerComboBox = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("Customer Login");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 0, 230, 42));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 135, 111, 29));

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel3.setText("Tel:");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 182, 111, 29));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Email:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 229, 111, 29));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("Date of Birth:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 276, 111, 29));
        add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 136, 178, -1));
        add(Tel, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 183, 178, -1));
        add(Email, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 230, 178, -1));
        add(Birth, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 277, 178, -1));

        LoginBtn.setBackground(new java.awt.Color(255, 255, 255));
        LoginBtn.setText("Login>>");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        add(LoginBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(505, 236, 112, -1));

        jLabel6.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel6.setText("User Name:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(499, 100, 168, -1));

        btnCreate.setBackground(new java.awt.Color(255, 255, 255));
        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });
        add(btnCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(244, 325, -1, -1));

        customerComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { }));
        customerComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerComboBoxActionPerformed(evt);
            }
        });
        add(customerComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(493, 157, 168, -1));

        jLabel9.setFont(new java.awt.Font("Malayalam MN", 1, 18)); // NOI18N
        jLabel9.setText("Create New Customer User");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(33, 79, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
        // TODO add your handling code here: 
        Customer cm =(Customer)customerComboBox.getSelectedItem();
        rightpanel.removeAll();
        ManageCustomerJpanel mcpanel = new ManageCustomerJpanel(rightpanel,csdirectory,airdir,fld,cm);
        this.rightpanel.add(mcpanel);
        ((java.awt.CardLayout)rightpanel.getLayout()).next(rightpanel);
           
    }//GEN-LAST:event_LoginBtnActionPerformed

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        // TODO add your handling code here:
        Customer cus = csdirectory.addCustomer();
        cus.setBirth(Birth.getText());
        cus.setEmail(Email.getText());
        cus.setName(Name.getText());
        cus.setTel(Tel.getText());
        
        
        if(Name.getText().equalsIgnoreCase("")){
            JOptionPane.showMessageDialog(null, "User name cannot be empty", "Warning", JOptionPane.INFORMATION_MESSAGE);
        }else{
            
//            for(Customer ctm : csdirectory.getCustomerdirectory()){
//            if(Name.getText().equalsIgnoreCase(ctm.getName())){
//                JOptionPane.showMessageDialog(null,"Username is repeated,please input a new one.");
//                return;
//            }
//        }
            Customer customer = csdirectory.addCustomer();
            customer.setName(Name.getText());
            
    
//            populate();
//        
//            JOptionPane.showMessageDialog(null, "Customer successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
       // }
        
        populate();

        JOptionPane.showMessageDialog(null, "Customer successfully added", "Warning", JOptionPane.INFORMATION_MESSAGE);
        /*customer.setBirth("");
        customer.setEmail("");
        customer.setName("");
        customer.setTel("");*/
        System.out.print(customer);
        }
        
    }//GEN-LAST:event_btnCreateActionPerformed

    private void customerComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_customerComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Birth;
    private javax.swing.JTextField Email;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JTextField Name;
    private javax.swing.JTextField Tel;
    private javax.swing.JButton btnCreate;
    private javax.swing.JComboBox customerComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
