/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import TravelAgency.Airliner;
import TravelAgency.AirlinerDirectory;
import TravelAgency.Customer;
import TravelAgency.CustomerDirectory;
import TravelAgency.FlightDirectory;
import TravelAgency.Order;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class ManageOrderJpanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageOrderJpanel
     */
    private JPanel rightpanel;
    private Customer customer;
    private AirlinerDirectory aird;
    private CustomerDirectory csdir;
    public ManageOrderJpanel(JPanel rightpanel,CustomerDirectory csdir,AirlinerDirectory aird,Customer customer) {
        initComponents();
        this.rightpanel = rightpanel;
        this.csdir = csdir;
        this.aird = aird;
        this.customer = customer;
        txtctmName.setText(customer.getName());
        populate();
        System.out.print(customer);
    }


    public void populate(){
        int rowCount = tblOrder.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)tblOrder.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        for(Airliner a : aird.getAirlinerDirectory()){
            for(Order order : customer.getOrderdirectory().getOrderdirectory()){
                    
                    SimpleDateFormat ymd =   new SimpleDateFormat( "yyyy-MM-dd" );
                    SimpleDateFormat hm =   new SimpleDateFormat( "HH:mm" );
        
            Object row[] = new Object[dtm.getColumnCount()];
            row[0] = order;
            row[1] = order.getFlight().getNum();
            row[2] = a.getName();
            row[3] = ymd.format(order.getFlight().getDate());
            row[4] = hm.format(order.getFlight().getDepaturetime());
            row[5] = hm.format(order.getFlight().getArrivetime());
            row[6] = order.getFlight().getFrom();
            row[7] = order.getFlight().getTo();
            row[8] = order.getSeat().getSeatPosition();
            row[9] = order.getFlight().getPrice();
            
            dtm.addRow(row);
            
        }
    }
    }
////    /**
////     * This method is called from within the constructor to initialize the form.
////     * WARNING: Do NOT modify this code. The content of this method is always
////     * regenerated by the Form Editor.
////     */
////    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRemove = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtctmName = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblOrder = new javax.swing.JTable();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnRemove.setBackground(new java.awt.Color(255, 255, 255));
        btnRemove.setText("Delete");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });
        add(btnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(952, 412, 150, -1));

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("Manage Order");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(382, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Myanmar MN", 1, 18)); // NOI18N
        jLabel2.setText("Customer Name:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 75, -1, -1));

        txtctmName.setEditable(false);
        txtctmName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtctmNameActionPerformed(evt);
            }
        });
        add(txtctmName, new org.netbeans.lib.awtextra.AbsoluteConstraints(176, 74, 150, -1));

        tblOrder.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order ID", "Flight Number", "Airliner Name", "Departure Date", "Departure Time", "Arrival Time", "Departure Location", "Arrival Location", "Seat Position", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblOrder);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 107, 1096, 272));
    }// </editor-fold>//GEN-END:initComponents

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        /*        // TODO add your handling code here:*/
        int selectedRow = tblOrder.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                Order o = (Order)tblOrder.getValueAt(selectedRow, 0);
                customer.getOrderdirectory().removeOrder(o);
                populate();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }
    }//GEN-LAST:event_btnRemoveActionPerformed

    private void txtctmNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtctmNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtctmNameActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRemove;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblOrder;
    private javax.swing.JTextField txtctmName;
    // End of variables declaration//GEN-END:variables
}
