/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;

import TravelAgency.AirPlane;
import TravelAgency.AirPlaneDirectory;
import TravelAgency.Airliner;
import TravelAgency.AirlinerDirectory;
import TravelAgency.Customer;
import TravelAgency.Flight;
import TravelAgency.FlightDirectory;
import java.awt.CardLayout;
import java.awt.Component;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author liumingyu
 */
public class SearchFlightJpanel extends javax.swing.JPanel {

    /**
     * Creates new form SearchFlightJpanel
     */
    private JPanel rightpanel;
    private FlightDirectory fld;
    private Customer customer;
    private AirlinerDirectory aird;
    private AirPlaneDirectory airpd;
    private Airliner airliner;
    private AirPlane airplane;
    private Flight flight;
    String depaturetime;
    String from;
    String to;
    String depaturedate;
    int timetype;
    
    public SearchFlightJpanel(JPanel rightpanel,FlightDirectory fld,Customer customer,AirlinerDirectory aird,AirPlaneDirectory airpd,Airliner airline,AirPlane airplane) {
        initComponents();
        this.rightpanel = rightpanel;
        this.customer = customer;
        this.aird = aird;
        TimeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { " ","Morning 06:00~12:00", "Afternoon 12:00~18:00", "Evening 18:00~06:00",}));
        add(TimeTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, -1));
        //System.out.print(customer);
 
    }

    
    public void viewall(){
        int rowCount = FlightTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)FlightTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        for(Airliner al : aird.getAirlinerDirectory()){
            for(AirPlane ap : al.getAirplanedirectory().getAirplanedirectory()){
                for(Flight f  : ap.getFlightDirectory().getFlightdirectory()){
                    SimpleDateFormat ymd = new SimpleDateFormat( "yyyy-MM-dd" );
                    SimpleDateFormat hm = new SimpleDateFormat( "HH:mm" );                    
                    Object row[] = new Object[dtm.getColumnCount()];
                    row[0] = f;
                    row[1] = al.getName();
                    row[2] = ymd.format(f.getDate());
                    row[3] = hm.format(f.getDepaturetime());
                    row[4] = f.getFrom();
                    row[5] = f.getTo();
                    row[6] = f.getPrice();
                    
            
            dtm.addRow(row);
                }
            }
        }
    }
    
    
    public void search(){
        int rowCount = FlightTable.getRowCount();
        DefaultTableModel dtm = (DefaultTableModel)FlightTable.getModel();
        for(int i = rowCount - 1; i >=0; i--) {
            dtm.removeRow(i);
        }
        for(Airliner al : aird.getAirlinerDirectory()){
            for(AirPlane ap : al.getAirplanedirectory().getAirplanedirectory()){
                for(Flight f  : ap.getFlightDirectory().SearchFlight(depaturedate,depaturetime,from,to,timetype)){
                    SimpleDateFormat ymd = new SimpleDateFormat( "yyyy-MM-dd" );
                    SimpleDateFormat hm = new SimpleDateFormat( "HH:mm" );
                    
                    Object row[] = new Object[dtm.getColumnCount()];
                    row[0] = f;
                    row[1] = al.getName();
                    row[2] = ymd.format(f.getDate());
                    row[3] = hm.format(f.getDepaturetime());
                    row[4] = f.getFrom();
                    row[5] = f.getTo();
                    row[6] = f.getPrice();
                    
            
            dtm.addRow(row);
            
                }
            }
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        DepatureDate = new javax.swing.JTextField();
        SearchBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        FlightTable = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        From = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        To = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        ViewAllFlightBtn = new javax.swing.JButton();
        TimeTypeComboBox = new javax.swing.JComboBox();
        BookBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 204, 204));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Myanmar MN", 1, 28)); // NOI18N
        jLabel1.setText("Search Flight");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(266, 6, 200, 42));

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel2.setText("Depature Date:");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(69, 89, -1, 30));
        add(DepatureDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(193, 90, 150, 30));

        SearchBtn.setBackground(new java.awt.Color(255, 255, 255));
        SearchBtn.setText("Search");
        SearchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBtnActionPerformed(evt);
            }
        });
        add(SearchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 175, 122, -1));

        FlightTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Flight Name", "Airliner Name", "Depature Date", "Depature Time", "From", "To", "Price"
            }
        ));
        jScrollPane1.setViewportView(FlightTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 691, 216));

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel4.setText("Depature Time:");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 126, -1, 30));

        From.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FromActionPerformed(evt);
            }
        });
        add(From, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 91, 133, -1));

        jLabel5.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel5.setText("From:");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 89, -1, 30));
        add(To, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 126, 133, 30));

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        jLabel6.setText("To:");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 125, -1, 30));

        ViewAllFlightBtn.setBackground(new java.awt.Color(255, 255, 255));
        ViewAllFlightBtn.setText("View All Flight");
        ViewAllFlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllFlightBtnActionPerformed(evt);
            }
        });
        add(ViewAllFlightBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(66, 175, -1, -1));

        TimeTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        add(TimeTypeComboBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 130, 160, -1));

        BookBtn.setText("Book>>");
        BookBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBtnActionPerformed(evt);
            }
        });
        add(BookBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(585, 500, 120, -1));

        jButton1.setText("Back<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 500, 120, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void FromActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FromActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FromActionPerformed

    private void ViewAllFlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllFlightBtnActionPerformed
        // TODO add your handling code here:    
         viewall();
    }//GEN-LAST:event_ViewAllFlightBtnActionPerformed

    private void SearchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBtnActionPerformed
        // TODO add your handling code here:        

        //depaturetime = DepatureTime.getText();
        from = From.getText();
        to = To.getText();
        depaturedate = DepatureDate.getText();
        timetype = TimeTypeComboBox.getSelectedIndex();
        //System.out.print(timetype);
        //System.out.print(to);
        search();
        
    }//GEN-LAST:event_SearchBtnActionPerformed

    private void BookBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBtnActionPerformed
        // TODO add your handling code here:
        int row = FlightTable.getSelectedRow();

        if(row<0) {
            JOptionPane.showMessageDialog(null, "Please select any row!!", "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        
        Flight f = (Flight)FlightTable.getValueAt(row, 0);
        BookingJpanel bookpanel = new BookingJpanel(rightpanel,customer,f);
        rightpanel.add(bookpanel);
        CardLayout layout = (CardLayout)rightpanel.getLayout();
        layout.next(rightpanel);
    }//GEN-LAST:event_BookBtnActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        CardLayout cardlayout =  (CardLayout)this.rightpanel.getLayout();
        Component[] comps = this.rightpanel.getComponents();
        cardlayout.previous(rightpanel);
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookBtn;
    private javax.swing.JTextField DepatureDate;
    private javax.swing.JTable FlightTable;
    private javax.swing.JTextField From;
    private javax.swing.JButton SearchBtn;
    private javax.swing.JComboBox TimeTypeComboBox;
    private javax.swing.JTextField To;
    private javax.swing.JButton ViewAllFlightBtn;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
